-- Add base_item_versions table for version history tracking
CREATE TABLE IF NOT EXISTS "vde_base_item_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vde_base_item_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"base_item_id" integer NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"preview" text,
	"link" text,
	"version_number" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	CONSTRAINT "vde_base_item_versions_base_item_id_version_number_unique" UNIQUE("base_item_id","version_number")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vde_base_item_versions" ADD CONSTRAINT "vde_base_item_versions_base_item_id_vde_base_items_id_fk" FOREIGN KEY ("base_item_id") REFERENCES "public"."vde_base_items"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vde_base_item_versions_base_item_id_idx" ON "vde_base_item_versions" USING btree ("base_item_id");
