import { type Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";
import colors from "tailwindcss/colors";

export default {
  darkMode: ["class"],
  content: ["./src/**/*.tsx"],
  safelist: [
    // Focus styles for toolbox
    "focus:outline-none",
    "focus-visible:outline-none",
    "focus:ring-2",
    "focus:ring-ring",
    "focus-visible:ring-2",
    "focus-visible:ring-ring",
    "focus-visible:ring-offset-2",
    "focus-visible:ring-offset-white",
    "dark:focus-visible:ring-offset-neutral-900",
    // Text colors for toolbox
    "text-primary",
    "text-secondary",
    "text-success",
    "text-link",
    "text-destructive",
    "text-neutral-700",
    "dark:text-neutral-300",
    // Depth-based text colors for tiles
    "text-white",
    "text-neutral-900",
    "dark:text-neutral-100",
    "dark:text-neutral-900",
    // Dark mode text colors for active tools
    "text-cyan-700",
    "dark:text-cyan-400",
    "text-indigo-700",
    "dark:text-indigo-300",
    "text-purple-700",
    "dark:text-purple-400",
    "text-green-700",
    "dark:text-green-400",
    "text-amber-700",
    "dark:text-amber-400",
    "text-rose-700",
    "dark:text-rose-400",
    // Hover text colors
    "hover:text-cyan-700",
    "dark:hover:text-cyan-400",
    "hover:text-indigo-700",
    "dark:hover:text-indigo-300",
    "hover:text-purple-700",
    "dark:hover:text-purple-400",
    "hover:text-green-700",
    "dark:hover:text-green-400",
    "hover:text-amber-700",
    "dark:hover:text-amber-400",
    "hover:text-rose-700",
    "dark:hover:text-rose-400",
    // Theme toggle hover and focus effects
    "group-hover:text-amber-400",
    "dark:group-hover:text-amber-400",
    "group-hover:text-violet-500",
    "group-hover:filter",
    "dark:group-hover:filter",
    "group-hover:drop-shadow-[0_0_6px_rgba(251,191,36,0.8)]",
    "dark:group-hover:drop-shadow-[0_0_6px_rgba(251,191,36,0.8)]",
    "group-hover:drop-shadow-[0_0_6px_rgba(139,92,246,0.8)]",
    "group-focus-visible:text-amber-400",
    "dark:group-focus-visible:text-amber-400",
    "group-focus-visible:text-violet-500",
    "group-focus-visible:filter",
    "dark:group-focus-visible:filter",
    "group-focus-visible:drop-shadow-[0_0_6px_rgba(251,191,36,0.8)]",
    "dark:group-focus-visible:drop-shadow-[0_0_6px_rgba(251,191,36,0.8)]",
    "group-focus-visible:drop-shadow-[0_0_6px_rgba(139,92,246,0.8)]",
    "filter",
    "drop-shadow-[0_0_6px_rgba(251,191,36,0.8)]",
    "drop-shadow-[0_0_6px_rgba(139,92,246,0.8)]",
    "drop-shadow-[0_0_8px_rgba(251,191,36,1)]",
    "drop-shadow-[0_0_8px_rgba(139,92,246,1)]",
    "dark:group-hover:drop-shadow-[0_0_8px_rgba(251,191,36,1)]",
    "group-hover:drop-shadow-[0_0_8px_rgba(139,92,246,1)]",
    "dark:group-focus-visible:drop-shadow-[0_0_8px_rgba(251,191,36,1)]",
    "group-focus-visible:drop-shadow-[0_0_8px_rgba(139,92,246,1)]",
    // Theme toggle pill darkening effect
    "bg-black/10",
    "dark:bg-black/20",
    "border-black/10",
    "dark:border-black/20",
    // Group hover text colors
    "group-hover:text-cyan-700",
    "dark:group-hover:text-cyan-400",
    "group-hover:text-indigo-700",
    "dark:group-hover:text-indigo-300",
    "group-hover:text-purple-700",
    "dark:group-hover:text-purple-400",
    "group-hover:text-green-700",
    "dark:group-hover:text-green-400",
    "group-hover:text-amber-700",
    "dark:group-hover:text-amber-400",
    "group-hover:text-rose-700",
    "dark:group-hover:text-rose-400",
    // Background colors for toolbox
    "bg-cyan-100",
    "dark:bg-cyan-900/20",
    "bg-cyan-900/20",
    "hover:bg-cyan-100",
    "dark:hover:bg-cyan-900/20",
    "bg-indigo-100", 
    "dark:bg-indigo-900/20",
    "bg-indigo-900/20",
    "hover:bg-indigo-100",
    "dark:hover:bg-indigo-900/20",
    "bg-purple-100",
    "dark:bg-purple-900/20",
    "bg-purple-900/20",
    "hover:bg-purple-100",
    "dark:hover:bg-purple-900/20",
    "bg-green-100",
    "dark:bg-green-900/20",
    "bg-green-900/20",
    "hover:bg-green-100",
    "dark:hover:bg-green-900/20",
    "bg-amber-100",
    "dark:bg-amber-900/20",
    "bg-amber-900/20",
    "hover:bg-amber-100",
    "dark:hover:bg-amber-900/20",
    "bg-rose-100",
    "dark:bg-rose-900/20",
    "bg-rose-900/20",
    "hover:bg-rose-100",
    "dark:hover:bg-rose-900/20",
    // Ring colors
    "ring-cyan-500",
    "ring-indigo-500",
    "ring-purple-500",
    "ring-green-500",
    "ring-amber-500",
    "ring-rose-500",
    // Hover ring effects
    "hover:ring-2",
    "hover:ring-inset",
    "hover:ring-cyan-500",
    "hover:ring-indigo-500",
    "hover:ring-purple-500",
    "hover:ring-green-500",
    "hover:ring-amber-500",
    "hover:ring-rose-500",
    "ring-inset",
    "!ring-2",
    "!ring-inset",
    "focus-visible:ring-inset",
    // Focus ring colors
    "focus-visible:ring-cyan-500",
    "focus-visible:ring-indigo-500",
    "focus-visible:ring-purple-500",
    "focus-visible:ring-green-500",
    "focus-visible:ring-amber-500",
    "focus-visible:ring-rose-500",
    // Semantic fill colors for tiles
    "fill-center-depth-0",
    "fill-center-depth-1",
    "fill-center-depth-2",
    "fill-center-depth-3",
    "fill-center-depth-4",
    "fill-center-depth-5",
    "fill-center-depth-6",
    "fill-center-depth-7",
    "fill-center-depth-8",
    "fill-nw-depth-1",
    "fill-nw-depth-2",
    "fill-nw-depth-3",
    "fill-nw-depth-4",
    "fill-nw-depth-5",
    "fill-nw-depth-6",
    "fill-nw-depth-7",
    "fill-nw-depth-8",
    "fill-ne-depth-1",
    "fill-ne-depth-2",
    "fill-ne-depth-3",
    "fill-ne-depth-4",
    "fill-ne-depth-5",
    "fill-ne-depth-6",
    "fill-ne-depth-7",
    "fill-ne-depth-8",
    "fill-e-depth-1",
    "fill-e-depth-2",
    "fill-e-depth-3",
    "fill-e-depth-4",
    "fill-e-depth-5",
    "fill-e-depth-6",
    "fill-e-depth-7",
    "fill-e-depth-8",
    "fill-se-depth-1",
    "fill-se-depth-2",
    "fill-se-depth-3",
    "fill-se-depth-4",
    "fill-se-depth-5",
    "fill-se-depth-6",
    "fill-se-depth-7",
    "fill-se-depth-8",
    "fill-sw-depth-1",
    "fill-sw-depth-2",
    "fill-sw-depth-3",
    "fill-sw-depth-4",
    "fill-sw-depth-5",
    "fill-sw-depth-6",
    "fill-sw-depth-7",
    "fill-sw-depth-8",
    "fill-w-depth-1",
    "fill-w-depth-2",
    "fill-w-depth-3",
    "fill-w-depth-4",
    "fill-w-depth-5",
    "fill-w-depth-6",
    "fill-w-depth-7",
    "fill-w-depth-8",
    // Old fill colors for tiles (for backward compatibility)
    "fill-amber-50",
    "fill-amber-100",
    "fill-amber-200",
    "fill-amber-300",
    "fill-amber-400",
    "fill-amber-500",
    "fill-amber-600",
    "fill-amber-700",
    "fill-amber-800",
    "fill-amber-900",
    "fill-amber-950",
    "fill-zinc-50",
    "fill-zinc-100",
    "fill-zinc-200",
    "fill-zinc-300",
    "fill-zinc-400",
    "fill-zinc-500",
    "fill-zinc-600",
    "fill-zinc-700",
    "fill-zinc-800",
    "fill-zinc-900",
    "fill-zinc-950",
    "fill-green-50",
    "fill-green-100",
    "fill-green-200",
    "fill-green-300",
    "fill-green-400",
    "fill-green-500",
    "fill-green-600",
    "fill-green-700",
    "fill-green-800",
    "fill-green-900",
    "fill-green-950",
    "fill-cyan-50",
    "fill-cyan-100",
    "fill-cyan-200",
    "fill-cyan-300",
    "fill-cyan-400",
    "fill-cyan-500",
    "fill-cyan-600",
    "fill-cyan-700",
    "fill-cyan-800",
    "fill-cyan-900",
    "fill-cyan-950",
    "fill-indigo-50",
    "fill-indigo-100",
    "fill-indigo-200",
    "fill-indigo-300",
    "fill-indigo-400",
    "fill-indigo-500",
    "fill-indigo-600",
    "fill-indigo-700",
    "fill-indigo-800",
    "fill-indigo-900",
    "fill-indigo-950",
    "fill-purple-50",
    "fill-purple-100",
    "fill-purple-200",
    "fill-purple-300",
    "fill-purple-400",
    "fill-purple-500",
    "fill-purple-600",
    "fill-purple-700",
    "fill-purple-800",
    "fill-purple-900",
    "fill-purple-950",
    "fill-rose-50",
    "fill-rose-100",
    "fill-rose-200",
    "fill-rose-300",
    "fill-rose-400",
    "fill-rose-500",
    "fill-rose-600",
    "fill-rose-700",
    "fill-rose-800",
    "fill-rose-900",
    "fill-rose-950",
    // Semantic color classes for toolbox buttons
    "bg-primary/10",
    "bg-primary/20",
    "dark:bg-primary/20",
    "bg-secondary/10",
    "bg-secondary/20",
    "dark:bg-secondary/20",
    "bg-success/10",
    "bg-success/20",
    "dark:bg-success/20",
    "bg-link/10",
    "bg-link/20",
    "dark:bg-link/20",
    "bg-destructive/10",
    "bg-destructive/20",
    "dark:bg-destructive/20",
    // Custom neutral background classes
    "bg-neutral-400/20",
    "dark:bg-neutral-600/20",
    // Widget background classes
    "bg-neutral-200/50",
    "dark:bg-neutral-700/50",
    "bg-neutral-200/40",
    "dark:bg-neutral-600/40",
    "bg-primary/8",
    "dark:bg-primary/12",
    "bg-destructive/8",
    "dark:bg-destructive/12",
    // Prose typography fixes for dark mode
    "prose-headings:text-foreground",
    "dark:prose-headings:text-foreground",
    "prose-h1:text-foreground",
    "prose-h2:text-foreground", 
    "prose-h3:text-foreground",
    "prose-h4:text-foreground",
    "prose-h5:text-foreground",
    "prose-h6:text-foreground",
    "dark:prose-h1:text-foreground",
    "dark:prose-h2:text-foreground",
    "dark:prose-h3:text-foreground", 
    "dark:prose-h4:text-foreground",
    "dark:prose-h5:text-foreground",
    "dark:prose-h6:text-foreground",
    // Prose blockquote fixes for both light and dark mode
    "prose-blockquote:text-foreground",
    "prose-blockquote:bg-muted/30",
    "prose-blockquote:border-l-4",
    "prose-blockquote:border-l-primary/60",
    "dark:prose-blockquote:text-foreground",
    "dark:prose-blockquote:bg-muted/30", 
    "dark:prose-blockquote:border-l-4",
    "dark:prose-blockquote:border-l-primary/60",
    // Prose list fixes for both light and dark mode
    "prose-li:text-foreground",
    "dark:prose-li:text-foreground",
    "prose-ul:text-foreground",
    "prose-ol:text-foreground", 
    "dark:prose-ul:text-foreground",
    "dark:prose-ol:text-foreground",
    "prose-p:text-foreground",
    "dark:prose-p:text-foreground",
    // Prose table and inline element fixes
    "prose-th:text-foreground",
    "prose-th:bg-muted/50",
    "prose-th:border-border",
    "prose-td:text-foreground",
    "prose-td:border-border",
    "prose-table:border-border",
    "dark:prose-th:text-foreground",
    "dark:prose-th:bg-muted/50",
    "dark:prose-th:border-border",
    "dark:prose-td:text-foreground",
    "dark:prose-td:border-border",
    "dark:prose-table:border-border",
    "prose-em:text-foreground",
    "dark:prose-em:text-foreground",
    "prose-strong:text-foreground",
    "dark:prose-strong:text-foreground",
    // Universal text color fix with !important for prose elements
    "[&_*]:!text-foreground",
    "[&_h1]:!text-foreground",
    "[&_h2]:!text-foreground", 
    "[&_h3]:!text-foreground",
    "[&_h4]:!text-foreground",
    "[&_h5]:!text-foreground",
    "[&_h6]:!text-foreground",
    "[&_p]:!text-foreground",
    "[&_li]:!text-foreground",
    "[&_th]:!text-foreground",
    "[&_td]:!text-foreground",
    "[&_blockquote]:!text-foreground",
    "[&_em]:!text-foreground",
    "[&_strong]:!text-foreground",
    "[&_blockquote]:bg-muted/30",
    "[&_blockquote]:border-l-4",
    "[&_blockquote]:border-l-primary/60",
    "[&_th]:bg-muted/50",
    "[&_th]:border-border",
    "[&_td]:border-border",
    "[&_table]:border-border",
    // Ring colors for toolbox buttons
    "ring-primary",
    "ring-secondary",
    "ring-success",
    "ring-link",
    "ring-destructive",
    // Text colors for toolbox buttons
    "text-primary",
    "text-secondary",
    "text-success",
    "text-link",
    "text-destructive",
    // Focus ring colors
    "focus-visible:ring-primary",
    "focus-visible:ring-secondary",
    "focus-visible:ring-success",
    "focus-visible:ring-link",
    "focus-visible:ring-destructive",
    // Canvas depth fill colors
    "fill-center-depth-0",
    "fill-center-depth-1",
    "fill-center-depth-2",
    "fill-center-depth-3",
    "fill-center-depth-4",
    "fill-center-depth-5",
    "fill-center-depth-6",
    "fill-center-depth-7",
    "fill-center-depth-8",
    "fill-nw-depth-1",
    "fill-nw-depth-2",
    "fill-nw-depth-3",
    "fill-nw-depth-4",
    "fill-nw-depth-5",
    "fill-nw-depth-6",
    "fill-nw-depth-7",
    "fill-nw-depth-8",
    "fill-ne-depth-1",
    "fill-ne-depth-2",
    "fill-ne-depth-3",
    "fill-ne-depth-4",
    "fill-ne-depth-5",
    "fill-ne-depth-6",
    "fill-ne-depth-7",
    "fill-ne-depth-8",
    "fill-e-depth-1",
    "fill-e-depth-2",
    "fill-e-depth-3",
    "fill-e-depth-4",
    "fill-e-depth-5",
    "fill-e-depth-6",
    "fill-e-depth-7",
    "fill-e-depth-8",
    "fill-se-depth-1",
    "fill-se-depth-2",
    "fill-se-depth-3",
    "fill-se-depth-4",
    "fill-se-depth-5",
    "fill-se-depth-6",
    "fill-se-depth-7",
    "fill-se-depth-8",
    "fill-sw-depth-1",
    "fill-sw-depth-2",
    "fill-sw-depth-3",
    "fill-sw-depth-4",
    "fill-sw-depth-5",
    "fill-sw-depth-6",
    "fill-sw-depth-7",
    "fill-sw-depth-8",
    "fill-w-depth-1",
    "fill-w-depth-2",
    "fill-w-depth-3",
    "fill-w-depth-4",
    "fill-w-depth-5",
    "fill-w-depth-6",
    "fill-w-depth-7",
    "fill-w-depth-8",
  ],

  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", ...fontFamily.sans],
      },
      colors: {
        primary: {
          DEFAULT: "rgb(var(--color-primary-rgb) / <alpha-value>)",
          light: "rgb(var(--color-primary-light-rgb) / <alpha-value>)",
          dark: "rgb(var(--color-primary-dark-rgb) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground))",
        },
        hex: {
          border: {
            DEFAULT: colors.slate[500],
            hover: colors.slate[800],
            selected: colors.violet[600],
          },
          fill: {
            DEFAULT: colors.slate[200],
            hover: colors.slate[300] + '80', // 50% opacity as hex
            selected: colors.violet[400] + 'CC', // 80% opacity as hex
          },
        },
        // Canvas depth colors
        'center-depth': {
          0: 'var(--color-center-depth-0)',
          1: 'var(--color-center-depth-1)',
          2: 'var(--color-center-depth-2)',
          3: 'var(--color-center-depth-3)',
          4: 'var(--color-center-depth-4)',
          5: 'var(--color-center-depth-5)',
          6: 'var(--color-center-depth-6)',
          7: 'var(--color-center-depth-7)',
          8: 'var(--color-center-depth-8)',
        },
        'nw-depth': {
          1: 'var(--color-nw-depth-1)',
          2: 'var(--color-nw-depth-2)',
          3: 'var(--color-nw-depth-3)',
          4: 'var(--color-nw-depth-4)',
          5: 'var(--color-nw-depth-5)',
          6: 'var(--color-nw-depth-6)',
          7: 'var(--color-nw-depth-7)',
          8: 'var(--color-nw-depth-8)',
        },
        'ne-depth': {
          1: 'var(--color-ne-depth-1)',
          2: 'var(--color-ne-depth-2)',
          3: 'var(--color-ne-depth-3)',
          4: 'var(--color-ne-depth-4)',
          5: 'var(--color-ne-depth-5)',
          6: 'var(--color-ne-depth-6)',
          7: 'var(--color-ne-depth-7)',
          8: 'var(--color-ne-depth-8)',
        },
        'e-depth': {
          1: 'var(--color-e-depth-1)',
          2: 'var(--color-e-depth-2)',
          3: 'var(--color-e-depth-3)',
          4: 'var(--color-e-depth-4)',
          5: 'var(--color-e-depth-5)',
          6: 'var(--color-e-depth-6)',
          7: 'var(--color-e-depth-7)',
          8: 'var(--color-e-depth-8)',
        },
        'se-depth': {
          1: 'var(--color-se-depth-1)',
          2: 'var(--color-se-depth-2)',
          3: 'var(--color-se-depth-3)',
          4: 'var(--color-se-depth-4)',
          5: 'var(--color-se-depth-5)',
          6: 'var(--color-se-depth-6)',
          7: 'var(--color-se-depth-7)',
          8: 'var(--color-se-depth-8)',
        },
        'sw-depth': {
          1: 'var(--color-sw-depth-1)',
          2: 'var(--color-sw-depth-2)',
          3: 'var(--color-sw-depth-3)',
          4: 'var(--color-sw-depth-4)',
          5: 'var(--color-sw-depth-5)',
          6: 'var(--color-sw-depth-6)',
          7: 'var(--color-sw-depth-7)',
          8: 'var(--color-sw-depth-8)',
        },
        'w-depth': {
          1: 'var(--color-w-depth-1)',
          2: 'var(--color-w-depth-2)',
          3: 'var(--color-w-depth-3)',
          4: 'var(--color-w-depth-4)',
          5: 'var(--color-w-depth-5)',
          6: 'var(--color-w-depth-6)',
          7: 'var(--color-w-depth-7)',
          8: 'var(--color-w-depth-8)',
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "rgb(var(--color-destructive-rgb) / <alpha-value>)",
          light: "rgb(var(--color-destructive-light-rgb) / <alpha-value>)",
          dark: "rgb(var(--color-destructive-dark-rgb) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground))",
        },
        // Semantic colors mapping to CSS variables (RGB format for opacity support)
        link: {
          DEFAULT: "rgb(var(--color-link-rgb) / <alpha-value>)",
          light: "rgb(var(--color-link-light-rgb) / <alpha-value>)",
          dark: "rgb(var(--color-link-dark-rgb) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--color-success-rgb) / <alpha-value>)",
          light: "rgb(var(--color-success-light-rgb) / <alpha-value>)",
          dark: "rgb(var(--color-success-dark-rgb) / <alpha-value>)",
        },
        info: {
          DEFAULT: "rgb(var(--color-link-rgb) / <alpha-value>)",
          light: "rgb(var(--color-link-light-rgb) / <alpha-value>)",
          dark: "rgb(var(--color-link-dark-rgb) / <alpha-value>)",
        },
        // Override secondary to use semantic color
        secondary: {
          DEFAULT: "rgb(var(--color-secondary-rgb) / <alpha-value>)",
          light: "rgb(var(--color-secondary-light-rgb) / <alpha-value>)",
          dark: "rgb(var(--color-secondary-dark-rgb) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground))",
        },
        // Add neutral color mapping to our CSS variables (using rgb() with <alpha-value> for opacity support)
        neutral: {
          50: "rgb(255 255 255 / <alpha-value>)",
          100: "rgb(248 249 250 / <alpha-value>)",
          200: "rgb(233 236 239 / <alpha-value>)",
          300: "rgb(222 226 230 / <alpha-value>)",
          400: "rgb(206 212 218 / <alpha-value>)",
          500: "rgb(173 181 189 / <alpha-value>)",
          600: "rgb(108 117 125 / <alpha-value>)",
          700: "rgb(73 80 87 / <alpha-value>)",
          800: "rgb(52 58 64 / <alpha-value>)",
          900: "rgb(33 37 41 / <alpha-value>)",
          950: "rgb(13 17 23 / <alpha-value>)",
        },
        // Add spatial color mappings for components still using them directly
        nw: {
          DEFAULT: "var(--color-nw)",
          light: "var(--color-nw-light)",
          dark: "var(--color-nw-dark)",
        },
        ne: {
          DEFAULT: "var(--color-ne)",
          light: "var(--color-ne-light)",
          dark: "var(--color-ne-dark)",
        },
        e: {
          DEFAULT: "var(--color-e)",
          light: "var(--color-e-light)",
          dark: "var(--color-e-dark)",
        },
        se: {
          DEFAULT: "var(--color-se)",
          light: "var(--color-se-light)",
          dark: "var(--color-se-dark)",
        },
        sw: {
          DEFAULT: "var(--color-sw)",
          light: "var(--color-sw-light)",
          dark: "var(--color-sw-dark)",
        },
        w: {
          DEFAULT: "var(--color-w)",
          light: "var(--color-w-light)",
          dark: "var(--color-w-dark)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: {
          DEFAULT: "rgb(var(--color-primary-rgb) / <alpha-value>)",
          primary: "rgb(var(--color-primary-rgb) / <alpha-value>)",
          secondary: "rgb(var(--color-secondary-rgb) / <alpha-value>)",
          success: "rgb(var(--color-success-rgb) / <alpha-value>)",
          link: "rgb(var(--color-link-rgb) / <alpha-value>)",
          destructive: "rgb(var(--color-destructive-rgb) / <alpha-value>)",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      spacing: {
        hex: "64px",
        "hex-spacing": "48px",
      },
      borderRadius: {
        hex: "12px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        float: "float 3s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": {
            transform: "translateY(0)",
          },
          "50%": {
            transform: "translateY(-5px)",
          },
        },
      },
      screens: {
        xs: "475px",
      },
      boxShadow: {
        hex: "0 0 15px -3px rgba(var(--color-primary-500), 0.3)",
        "hex-hover": "0 0 20px -2px rgba(var(--color-primary-500), 0.4)",
      },
      transitionTimingFunction: {
        hex: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: "65ch",
            color: "var(--color-primary-950)",
            h1: {
              color: "var(--color-primary-900)",
            },
            h2: {
              color: "var(--color-primary-800)",
            },
            h3: {
              color: "var(--color-primary-700)",
            },
            strong: {
              color: "var(--color-primary-900)",
            },
            a: {
              color: "var(--color-secondary-600)",
              "&:hover": {
                color: "var(--color-secondary-700)",
              },
            },
          },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"), 
    require("tailwindcss-animate"), 
    require("tailwind-scrollbar"),
    require("./tailwind-plugin-validate-colors"),
  ],
} satisfies Config;
